import fs from 'node:fs';
import path from 'node:path';

function removePathIfPresent(targetPath) {
  try {
    fs.rmSync(targetPath, { recursive: true, force: true });
  } catch (error) {
    void error;
    // ignore cleanup failures
  }
}

function ensureParent(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFile(filePath, content, mode) {
  ensureParent(filePath);
  fs.writeFileSync(filePath, content, 'utf8');
  if (typeof mode === 'number') {
    fs.chmodSync(filePath, mode);
  }
}

function writeJson(filePath, value) {
  writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function isSymlink(filePath) {
  try {
    return fs.lstatSync(filePath).isSymbolicLink();
  } catch {
    return false;
  }
}

function isManagedWorkflowWrapper(content, { requiresAliasMap = false } = {}) {
  if (typeof content !== 'string' || content.length === 0) {
    return false;
  }

  const sharedMarkers = [
    "require('node:child_process')",
    'spawnSync(process.execPath',
    "'--state'",
    "process.exit(typeof result.status === 'number' ? result.status : 1);",
  ];

  if (!sharedMarkers.every((marker) => content.includes(marker))) {
    return false;
  }

  if (!requiresAliasMap) {
    return true;
  }

  return content.includes('const aliasMap = new Map([');
}

function shouldRefreshRootWorkflowWrapper(filePath) {
  if (!fs.existsSync(filePath)) {
    return true;
  }

  try {
    return isManagedWorkflowWrapper(fs.readFileSync(filePath, 'utf8'), { requiresAliasMap: true });
  } catch {
    return false;
  }
}

function relativeTarget(fromPath, toPath) {
  return path.relative(path.dirname(fromPath), toPath) || '.';
}

function createSymlinkOrCopy({ linkPath, targetPath, type = 'file' }) {
  ensureParent(linkPath);

  try {
    if (fs.existsSync(linkPath) || fs.lstatSync(linkPath)) {
      removePathIfPresent(linkPath);
    }
  } catch (error) {
    void error;
    // ignore cleanup misses
  }

  try {
    fs.symlinkSync(relativeTarget(linkPath, targetPath), linkPath, type);
    return 'symlink';
  } catch {
    const stats = fs.statSync(targetPath);
    if (stats.isDirectory()) {
      fs.cpSync(targetPath, linkPath, { recursive: true });
    } else {
      fs.copyFileSync(targetPath, linkPath);
    }
    return 'copy';
  }
}

function createIfMissing(createdPaths, { linkPath, targetPath, type = 'file' }) {
  if (fs.existsSync(linkPath)) {
    return null;
  }

  const mode = createSymlinkOrCopy({ linkPath, targetPath, type });
  createdPaths.push(linkPath);
  return mode;
}

function syncJsonMirror(targetPath, sourcePath) {
  if (!fs.existsSync(sourcePath)) {
    return;
  }

  writeJson(targetPath, readJson(sourcePath));
}

export function ensureWorkspaceShim(paths) {
  const createdPaths = [];

  fs.mkdirSync(paths.workspaceShimDir, { recursive: true });

  createIfMissing(createdPaths, {
    linkPath: paths.workspaceShimAgentsPath,
    targetPath: path.join(paths.kitRoot, 'AGENTS.md'),
    type: 'file',
  });

  createIfMissing(createdPaths, {
    linkPath: paths.workspaceShimContextDir,
    targetPath: path.join(paths.kitRoot, 'context'),
    type: 'dir',
  });

  createIfMissing(createdPaths, {
    linkPath: paths.workspaceShimTemplatesDir,
    targetPath: path.join(paths.kitRoot, 'docs', 'templates'),
    type: 'dir',
  });

  createIfMissing(createdPaths, {
    linkPath: paths.workspaceShimWorkflowStatePath,
    targetPath: paths.workflowStatePath,
    type: 'file',
  });

  if (fs.existsSync(paths.workflowStatePath)) {
    syncJsonMirror(paths.workspaceShimWorkflowStatePath, paths.workflowStatePath);
  }

  const workflowCli = `#!/usr/bin/env node
// Generated by OpenKit workspace shim.
const { spawnSync } = require('node:child_process');

const rawArgs = process.argv.slice(2);
const command = rawArgs[0];
const aliasMap = new Map([
  ['get', 'show'],
  ['--help', 'help'],
  ['-h', 'help'],
]);
const normalizedArgs = rawArgs.length === 0 ? ['help'] : [aliasMap.get(command) ?? command, ...rawArgs.slice(1)];
const result = spawnSync(process.execPath, [${JSON.stringify(path.join(paths.kitRoot, '.opencode', 'workflow-state.js'))}, '--state', ${JSON.stringify(paths.workflowStatePath)}, ...normalizedArgs], {
  stdio: 'inherit',
  env: {
    ...process.env,
    OPENKIT_PROJECT_ROOT: ${JSON.stringify(paths.projectRoot)},
  },
});

if (result.error) {
  throw result.error;
}

process.exit(typeof result.status === 'number' ? result.status : 1);
`;

  const profileSwitchCli = `#!/usr/bin/env node
// Generated by OpenKit workspace shim.
const { spawnSync } = require('node:child_process');

const result = spawnSync(process.execPath, [${JSON.stringify(path.join(paths.kitRoot, 'src', 'runtime', 'profile-switch-cli.js'))}, ...process.argv.slice(2)], {
  stdio: 'inherit',
  env: {
    ...process.env,
    OPENKIT_PROJECT_ROOT: ${JSON.stringify(paths.projectRoot)},
    OPENKIT_WORKFLOW_STATE: ${JSON.stringify(paths.workflowStatePath)},
    OPENKIT_KIT_ROOT: ${JSON.stringify(paths.kitRoot)},
  },
});

if (result.error) {
  throw result.error;
}

process.exit(typeof result.status === 'number' ? result.status : 1);
`;

  const switchProfilesCli = `#!/usr/bin/env node
// Generated by OpenKit workspace shim.
const { spawnSync } = require('node:child_process');

const result = spawnSync(process.execPath, [${JSON.stringify(path.join(paths.kitRoot, 'src', 'runtime', 'switch-profiles-cli.js'))}, ...process.argv.slice(2)], {
  stdio: 'inherit',
  env: {
    ...process.env,
    OPENKIT_PROJECT_ROOT: ${JSON.stringify(paths.projectRoot)},
    OPENKIT_WORKFLOW_STATE: ${JSON.stringify(paths.workflowStatePath)},
    OPENKIT_KIT_ROOT: ${JSON.stringify(paths.kitRoot)},
  },
});

if (result.error) {
  throw result.error;
}

process.exit(typeof result.status === 'number' ? result.status : 1);
`;

  const workspaceWrapperExists = fs.existsSync(paths.workspaceShimWorkflowCliPath);
  writeFile(paths.workspaceShimWorkflowCliPath, workflowCli, 0o755);
  if (!workspaceWrapperExists) {
    createdPaths.push(paths.workspaceShimWorkflowCliPath);
  }

  const workspaceProfileSwitchPath = path.join(paths.workspaceShimDir, 'profile-switch.js');
  const workspaceProfileSwitchExists = fs.existsSync(workspaceProfileSwitchPath);
  writeFile(workspaceProfileSwitchPath, profileSwitchCli, 0o755);
  if (!workspaceProfileSwitchExists) {
    createdPaths.push(workspaceProfileSwitchPath);
  }

  const workspaceSwitchProfilesPath = path.join(paths.workspaceShimDir, 'switch-profiles.js');
  const workspaceSwitchProfilesExists = fs.existsSync(workspaceSwitchProfilesPath);
  writeFile(workspaceSwitchProfilesPath, switchProfilesCli, 0o755);
  if (!workspaceSwitchProfilesExists) {
    createdPaths.push(workspaceSwitchProfilesPath);
  }

  createIfMissing(createdPaths, {
    linkPath: path.join(paths.projectRoot, 'AGENTS.md'),
    targetPath: paths.workspaceShimAgentsPath,
    type: 'file',
  });

  createIfMissing(createdPaths, {
    linkPath: path.join(paths.projectRoot, 'context'),
    targetPath: paths.workspaceShimContextDir,
    type: 'dir',
  });

  const rootWorkflowStateMode = createIfMissing(createdPaths, {
    linkPath: path.join(paths.projectRoot, '.opencode', 'workflow-state.json'),
    targetPath: paths.workspaceShimWorkflowStatePath,
    type: 'file',
  });

  const rootWorkflowStatePath = path.join(paths.projectRoot, '.opencode', 'workflow-state.json');
  if (fs.existsSync(paths.workflowStatePath) && (rootWorkflowStateMode !== null || isSymlink(rootWorkflowStatePath))) {
    syncJsonMirror(rootWorkflowStatePath, paths.workflowStatePath);
  }

  if (shouldRefreshRootWorkflowWrapper(path.join(paths.projectRoot, '.opencode', 'workflow-state.js'))) {
    const rootWorkflowCli = `#!/usr/bin/env node
// Generated by OpenKit workspace shim.
const { spawnSync } = require('node:child_process');

const rawArgs = process.argv.slice(2);
const command = rawArgs[0];
const aliasMap = new Map([
  ['get', 'show'],
  ['--help', 'help'],
  ['-h', 'help'],
]);
const normalizedArgs = rawArgs.length === 0 ? ['help'] : [aliasMap.get(command) ?? command, ...rawArgs.slice(1)];
const result = spawnSync(process.execPath, [${JSON.stringify(path.join(paths.kitRoot, '.opencode', 'workflow-state.js'))}, '--state', ${JSON.stringify(paths.workflowStatePath)}, ...normalizedArgs], {
  stdio: 'inherit',
  env: {
    ...process.env,
    OPENKIT_PROJECT_ROOT: ${JSON.stringify(paths.projectRoot)},
  },
});

if (result.error) {
  throw result.error;
}

process.exit(typeof result.status === 'number' ? result.status : 1);
`;

    const rootWorkflowCliPath = path.join(paths.projectRoot, '.opencode', 'workflow-state.js');
    const rootWrapperExists = fs.existsSync(rootWorkflowCliPath);
    writeFile(rootWorkflowCliPath, rootWorkflowCli, 0o755);
    if (!rootWrapperExists) {
      createdPaths.push(rootWorkflowCliPath);
    }
  }

  const rootProfileSwitchPath = path.join(paths.projectRoot, '.opencode', 'profile-switch.js');
  const rootProfileSwitchExists = fs.existsSync(rootProfileSwitchPath);
  writeFile(rootProfileSwitchPath, profileSwitchCli, 0o755);
  if (!rootProfileSwitchExists) {
    createdPaths.push(rootProfileSwitchPath);
  }

  const rootSwitchProfilesPath = path.join(paths.projectRoot, '.opencode', 'switch-profiles.js');
  const rootSwitchProfilesExists = fs.existsSync(rootSwitchProfilesPath);
  writeFile(rootSwitchProfilesPath, switchProfilesCli, 0o755);
  if (!rootSwitchProfilesExists) {
    createdPaths.push(rootSwitchProfilesPath);
  }

  if (!fs.existsSync(path.join(paths.projectRoot, '.opencode', 'work-items'))) {
    createIfMissing(createdPaths, {
      linkPath: path.join(paths.projectRoot, '.opencode', 'work-items'),
      targetPath: paths.workItemsDir,
      type: 'dir',
    });
  }

  createIfMissing(createdPaths, {
    linkPath: paths.workspaceShimWorkItemsDir,
    targetPath: paths.workItemsDir,
    type: 'dir',
  });

  return {
    paths,
    createdPaths,
  };
}

export function cleanupWorkspaceShim(shim) {
  if (!shim?.createdPaths) {
    return;
  }

  for (const createdPath of [...shim.createdPaths].reverse()) {
    removePathIfPresent(createdPath);
  }

  const maybeShimDir = shim.paths?.workspaceShimDir;
  if (maybeShimDir && fs.existsSync(maybeShimDir)) {
    try {
      const entries = fs.readdirSync(maybeShimDir);
      if (entries.length === 0) {
        removePathIfPresent(maybeShimDir);
      }
    } catch (error) {
      void error;
      // ignore cleanup misses
    }
  }
}
